#!/bin/sh /etc/rc.common
START=18
STOP=89
USE_PROCD=1
start_service() {
 procd_open_instance guard
 procd_set_param command /bin/sh /root/router-project/scripts/transaction.sh watch
 procd_set_param respawn 3600 2 0
 procd_set_param stdout 1
 procd_set_param stderr 1
 procd_close_instance
}
